/* eslint-disable one-var */
export const SET_USERINFO = 'SET_USERINFO'
export const SET_TOKEN = 'SET_TOKEN'
export const ADD_ERROR_INFO = 'ADD_ERROR_INFO'
export const SET_LANGUAGE = 'SET_LANGUAGE'
export const SET_I18N_LANGUAGE = 'SET_I18N_LANGUAGE'
export const SET_THEME = 'SET_THEME'
export const SET_PATH = 'SET_PATH'
export const SET_LEFT_SIDE_BAR_STATUS = 'SET_LEFT_SIDE_BAR_STATUS'
export const SET_MT4_ACCOUNTS = 'SET_MT4_ACCOUNTS'
export const SET_MT4_TRADER_ACCOUNTS = 'SET_MT4_TRADER_ACCOUNTS'
export const SET_MT4_AGENT_ACCOUNTS = 'SET_MT4_AGENT_ACCOUNTS'
export const SET_LEVERAGE = 'SET_LEVERAGE'
export const SET_CONTENT_LOADING = 'SET_CONTENT_LOADING' // 页面内容loading,不会遮盖菜单，一般用于页面内容加载的时候
export const SET_NOTICE_REFRESH_FLAG = 'SET_NOTICE_REFRESH_FLAG'
export const SET_TERMS = 'SET_TERMS'
export const SET_SYNC_TIME = 'SET_SYNC_TIME'
export const SET_ASYNC_LOADING = 'SET_ASYNC_LOADING' // 异步请求数据时的loading，会遮盖菜单，整个页面都不能交互
export const SET_FETCH_PENDING = 'SET_FETCH_PENDING'
export const SET_NEED_VIDEO_AUTHEN = 'SET_NEED_VIDEO_AUTHEN' //  设置是否需要视频认证
export const SET_AUTH_VIDEOS = 'SET_AUTH_VIDEOS'
