
export const SET_USERINFO = 'SET_USERINFO'
export const SET_TOKEN = 'SET_TOKEN'
export const ADD_ERROR_INFO = 'ADD_ERROR_INFO'
export const SET_LANGUAGE = 'SET_LANGUAGE'
export const SET_THEME = 'SET_THEME'
export const SET_PATH = 'SET_PATH'
export const SET_LEFT_SIDE_BAR_STATUS = "SET_LEFT_SIDE_BAR_STATUS"
export const SET_MT4_ACCOUNTS = "SET_MT4_ACCOUNTS"
export const SET_MT4_TRADER_ACCOUNTS = "SET_MT4_TRADER_ACCOUNTS"
export const SET_MT4_AGENT_ACCOUNTS = "SET_MT4_AGENT_ACCOUNTS"
export const SET_LEVERAGE = "SET_LEVERAGE"
export const SET_CONTENT_LOADING = " SET_CONTENT_LOADING"
