export default {
  zh: {
    email: '邮件',
    password: '密码',
    confirm_password: '新输入密码',
    old_password: '当前密码',
    positiveFloatMoney: '金额',
    bank: '银行账户',
    startDate: '开始时间',
    endDate: '结束时间',
    withdraw_pay: '出金',
    withdraw_pay_doku: 'Doku 出金',
    withdraw_pay_fasa: 'Fasa 出金',
    deposit_pay: '入金',
    origin_login: '转出资金账户',
    target_login: '转入资金账户',
    money: '金额',
    terms: '条款',
    phone: '预留电话号码',
    bankName: '银行名称',
    bankAccount: '银行账号',
    bankProvince: '银行省份',
    bankCity: '银行城市',
    branchName: '支行名称',
    swift: 'Swift号',
    bankDocument: '账单',
    backCreditCard: '信用卡反面照片',
    frontCreditCard: '信用卡正面照片',
    withdrawMethod: '出金方式',
    accountType: '账户类型',
    platForm: '交易平台',
    lever: '杠杆',
    baseCurrency: '基本货币',
    keywords: '搜索关键字',
    account: '账户',
    questionType: '工单类型',
    content: '内容',
    service_comment: '服务和营销策略',
    exp_comment: '外汇相关经验',
    exp_company: '代理过的公司',
    subject: '主题',
    firstSix: '前六位',
    lastFour: '后四位'
  },
  zhHant: {
    email: '郵件',
    password: '密碼',
    confirm_password: '新輸入密碼',
    old_password: '當前密碼',
    positiveFloatMoney: '金額',
    bank: '銀行賬戶',
    startDate: '開始時間',
    endDate: '結束時間',
    withdraw_pay: '出金',
    withdraw_pay_doku: 'Doku 出金',
    withdraw_pay_fasa: 'Fasa 出金',
    deposit_pay: '入金',
    origin_login: '轉出資金賬戶',
    target_login: '轉入資金賬戶',
    money: '金額',
    terms: '條款',
    phone: '預留電話號碼',
    bankName: '銀行名稱',
    bankAccount: '銀行賬號',
    bankProvince: '銀行省份',
    bankCity: '銀行城市',
    branchName: '支行名稱',
    swift: 'Swift號',
    bankDocument: '賬單',
    backCreditCard: '信用卡反面照片',
    frontCreditCard: '信用卡正面照片',
    withdrawMethod: '出金方式',
    accountType: '賬戶類型',
    platForm: '交易平台',
    lever: '槓桿',
    baseCurrency: '基本貨幣',
    keywords: '搜索關鍵字',
    account: '賬戶',
    questionType: '工單類型',
    content: '內容',
    service_comment: '服務和營銷策略',
    exp_comment: '外匯相關經驗',
    exp_company: '代理過的公司',
    subject: '主題',
    firstSix: '前六位',
    lastFour: '後四位'
  },
  en: {
    email: 'Email address',
    password: 'Password',
    confirm_password: 'Confirmed Password',
    old_password: 'Current Password',
    positiveFloatMoney: 'Currency',
    bank: 'Bank Account',
    startDate: 'Start Date',
    endDate: 'End Date',
    withdraw_pay: 'Withdraw amount',
    withdraw_pay_doku: 'Doku withdraw',
    withdraw_pay_fasa: 'Fasa withdraw',
    deposit_pay: 'Deposite amount',
    origin_login: 'Origin account',
    target_login: 'Target account',
    money: 'Currency',
    terms: 'Terms',
    phone: 'Account Phone Number',
    bankName: 'Bank Name',
    bankAccount: 'Account number',
    bankProvince: 'Bank Province',
    bankCity: 'Bank ',
    branchName: 'Bank branch name',
    swift: 'Swift code',
    bankDocument: 'Bank document',
    backCreditCard: 'Back side of credit card',
    frontCreditCard: 'Front side of credit card',
    withdrawMethod: 'Withdraw method',
    accountType: 'Account type',
    platForm: 'Platform',
    lever: 'Leverage',
    baseCurrency: 'Base currency',
    keywords: 'Key words',
    account: 'Account',
    questionType: 'Question Type',
    content: 'Content',
    service_comment: ' your services comments',
    exp_comment: 'your experience with FOREX or any related experience',
    exp_company: 'Other Affiliate FX companies',
    subject: 'Subject',
    firstSix: 'First Six Card Numbers',
    lastFour: 'Last Four Card Numbers'
  }
}
