export default {
  zh:{
    email : "邮件",
    password : "密码",
    confirm_password : "新输入密码",
    old_password : "当前密码",
    positiveFloatMoney : "金额",
    bank : "银行账户",
    startDate : "开始时间",
    endDate : "结束时间",
    withdraw_pay : "出金",
    withdraw_pay_doku : "Doku 出金",
    withdraw_pay_fasa : "Fasa 出金",
    deposit_pay:"入金",
    origin_login:"转出资金账户",
    target_login:"转入资金账户",
    money:"金额",
    terms:"条款",
    bankName : "银行名称",
    bankAccount : "银行账号",
    bankProvince : "银行省份",
    bankCity : "银行城市",
    branchName : "支行名称",
    swift : "Swift号",
    bankDocument : "账单",
    withdrawMethod:"出金方式",
    accountType : "账户类型",
    platForm : "交易平台",
    lever : "杠杆",
    baseCurrency : "基本货币",
    keywords: "搜索关键字",
    account: "账户",
    questionType: "工单类型",
    content:"内容"
  },
  en:{
    email : "Email address",
    password : "Password",
    confirm_password : "Confirmed Password",
    old_password : "Current Password",
    positiveFloatMoney : "Currency",
    bank : "Bank Account",
    startDate : "Start Date",
    endDate : "End Date",
    withdraw_pay : "Withdraw amount",
    withdraw_pay_doku:"Doku withdraw",
    withdraw_pay_fasa : "Fasa withdraw",
    deposit_pay:"Deposite amount",
    origin_login:"Origin account",
    target_login:"Target account",
    money:"Currency",
    terms : "Terms",
    bankName : "Bank Name",
    bankAccount : "Account number",
    bankProvince : "Bank Province",
    bankCity : "Bank ",
    branchName : "Bank branch name",
    swift : "Swift code",
    bankDocument : "Bank document",
    withdrawMethod : "Withdraw method",
    accountType : "Account type",
    platForm : "Platform",
    lever : "Leverage",
    baseCurrency : "Base currency",
    keywords: "Key words",
    account: "Account",
    questionType:"Question Type",
    content:"Content"
  }
}
